Replace Vue CLI with Vite
fluidpay/fluidpay-tokenizer pull request #56
Opened 2024-11-13 09:52 UTC by ngygbr

Replace Vue CLI with Vite

2024-11-13 11:26 UTC, borosr requested changes

2024-11-13 11:26 UTC, borosr commented on src/docs/vite.config.ts
> +        port: 1111
Please add a different port from the 8xxx range,

2024-11-13 12:42 UTC, borosr approved these changes

2024-11-13 16:59 UTC, bvoelker approved these changes
Much cleaner. I might do one more round of cleanup but at long as the build output is the same we should be good.

2025-02-10 16:39 UTC, bvoelker commented
Sorry for the delay on this. im going to merge this in and ill play with this locally to make sure everything is still working as it should. Thank you again.

2025-02-10 16:39 UTC, merged